lab2c:	lab2c.c SortedList.h SortedList.c
	gcc -g -o lab2c lab2c.c SortedList.h SortedList.c -pthread

dist:
	tar -cvzf lab2c-804483463.tar.gz SortedList.h SortedList.c lab2c.c Makefile README lab2c-graph1.png
clean:
	rm -rf *.o lab2c
